### ISSUE TITLE
Several Items not updateing

### ISSUE THREAD

**Issue by br41n79** [Gaspode69/ioBroker.alpha-ess#128]
Since 2 days the folowing is not updating: 

Grid_consumption_today
Generation_today
Grid_feed_in_today

Even after update/ reboot/ etc.

**Comment by Gaspode69** [comment]
This is an Open API Issue, see https://github.com/alphaess-developer/alphacloud_open_api/issues/82

**Comment by br41n79** [comment]
Thanks for the (very) fast response! 
Si, ill wait and add it manually into my database unti its fixed ;)

**Comment by Gaspode69** [comment]
Alpha-ESS fixed the issue.
