### ISSUE TITLE
Summary.Generation_total not updating

### ISSUE THREAD

**Issue by br41n79** [Gaspode69/ioBroker.alpha-ess#137]
Hi Gaspode, 

since the update from Alpha, the names Object isnt updating any longer. 
No entry in the logfile or any other error/ issue is shown. 

Best
br41n

**Comment by Gaspode69** [comment]
> the names Object

?

Have you tried to restart the adapter?

**Comment by br41n79** [comment]
Restarted/ reinstalled… 😕

Summary.Generation_total


Gaspode69 ***@***.***> schrieb am Do. 24. Okt. 2024 um 08:09:

**Comment by Gaspode69** [comment]
What is the timestamp of the value? Is it really not updated at all or updated with old values?

But anyway, there are still problems with the Open API by Alpha-ESS, so please open a ticket there an describe the problem.

Use something like "For API call getSumDataForCustomer the attribute epvtotal is not delivered properly" and describe exactly what's going on (if the timestamp is actual, then you can assume that the API deliveres the same old value over and over again)

Sorry, that's all I can do.

**Comment by br41n79** [comment]
Hey no worries, thanks for the hint. Mit freundlichen Grüßen - Yours sincerely Michael Brück Diese E-Mail samt Anlagen ist vertraulich und nur für den genannten Empfänger bestimmt. Sollten Sie diese E-Mail-Nachricht versehentlich erhalten haben, so unterrichten Sie bitte hierüber den Absender und löschen Sie bitte endgültig alle erhaltenen Informationen. Sie sind nicht befugt, unbeabsichtigt erhaltene Informationen Dritten zu offenbaren, sie zu kopieren, weiterzuleiten oder in sonstiger Weise zu verwenden.Am 24.10.2024 um 08:48 schrieb Gaspode69 ***@***.***>:﻿
What is the timestamp of the value? Is it really not updated at all or updated with old values?
But anyway, there are still problems with the Open API by Alpha-ESS, so please open a ticket there an describe the problem.
Use something like "For API call getSumDataForCustomer the attribute epvtotal is not delivered properly" and describe exactly what's going on (if the timestamp is actual, then you can assume that the API deliveres the same old value over and over again)
Sorry, that's all I can do.

**Comment by Gaspode69** [comment]
See also [here](https://www.storion4you.de/thread/1431-serverumzug-cloud-nicht-erreichbar-kein-monitoring/?postID=15363#post15363)
