### ISSUE TITLE
Settings_Discharge.Discharging_Cutoff_SOC

### ISSUE THREAD

**Issue by WilliLz** [Gaspode69/ioBroker.alpha-ess#144]
in spring changing of discharge cutoff SOC was possible by ioBroker object "Discharging Cutoff SOC [batUseCap]"
now it doesn't work. (probably since server change?)

changes on smartphone app and website https://cloud.alphaess.com/index works.
installed version: ioBroker.alpha-ess 2.1.4

(über den Datenpunkt "Discharging Cutoff SOC [batUseCap]" kann die Mindestladekapazität des Akkus nicht mehr gesetzt werden.

**Comment by Gaspode69** [comment]
There are still problems with the Open API by Alpha-ESS, so please open a ticket there an describe the problem.
Mention, that batUseCap can not be set using the Alpha-ESS API.
Sorry, there is nothing, I can do. Problem is caused by Alpha-ESS.

**Comment by WilliLz** [comment]
many thanks, I opened a ticket on Alpha-ESS

**Comment by WilliLz** [comment]
Today I've got the following answer:
```
Ticket Number:CAS-126865

SN:ALB00xxxxxxxxx

Sehr geehrte/r Kundin/e,

Ihr Ticket wurde erfolgreich gelöst.Helfen Sie uns mit Ihrem Feedback dabei, unsere Prozesse weiterhin zu optimieren um stetig besser zu werden. Vielen Dank für Ihre Zusammenarbeit.

Dies ist eine automatisch generierte E-Mail, bitte antworten Sie nicht auf diese E-Mail.

Mit freundlichen Grüßen

Ihr AlphaEss Service Team
```
but it didn't work. Must there be anything changed?

**Comment by Gaspode69** [comment]
AFAIk not on your/my side. According to the documentation it should work as implemented.

**Comment by WilliLz** [comment]
a missing information, sorry I sent mail information not the answer from ticket system
```
Betreff: Unterstützung bei der Open API und [batUseCap]

Sehr geehrter Kunde,

vielen Dank für Ihre Nachricht und die Hinweise zu den Änderungen nach dem letzten Update der Open API.

Aktuell haben wir technische Probleme mit der Open API, die die Funktionalität zur Einstellung des Entladegrenzwerts (Discharging Cutoff SOC) über den Datenpunkt "[batUseCap]" beeinträchtigen. Unsere Entwickler arbeiten bereits an einer Lösung und erwarten, dass diese bis spätestens Donnerstag dieser Woche behoben ist.

Wir danken Ihnen für Ihre Geduld und Ihr Verständnis. Bitte versuchen Sie es nach der Behebung erneut, und lassen Sie uns wissen, ob weiterhin Probleme auftreten.

Mit freundlichen Grüßen,

Simin Zhao
Ihr Alphaess Team
```

**Comment by Gaspode69** [comment]
Thanks for the info. 👍

**Comment by WilliLz** [comment]
"Discharging Cutoff SOC [batUseCap]" setting works again, just tested a few minutes ago. 
Thanks to Alpaess Team
