### ISSUE TITLE
Adapter ist running 

### ISSUE THREAD

**Issue by Gavor69** [Gaspode69/ioBroker.alpha-ess#71]
**Describe the bug**  
Since yesterday morning, the real-time data in the iobroker obkejten are no longer updated.
The log says that the login is not correct. In my opinion, I have not changed anything.

**Screenshots & Logfiles**  
<html>
<body>

alpha-ess.1 | 2023-11-05 09:19:33.114 | error | authenticate Exception occurred: TypeError: Cannot read properties of undefined (reading 'AccessToken')
-- | -- | -- | --
alpha-ess.1 | 2023-11-05 09:19:32.571 | info | Try to login
alpha-ess.1 | 2023-11-05 09:19:32.490 | warn | Settings: Five or more errors occurred, next request in 5 minutes.
alpha-ess.1 | 2023-11-05 09:19:32.486 | warn | Error in Authorization (error count: 7)
alpha-ess.1 | 2023-11-05 09:19:32.466 | error | authenticate Exception occurred: TypeError: Cannot read properties of undefined (reading 'AccessToken')
alpha-ess.1 | 2023-11-05 09:19:31.916 | info | Try to login

</body>
</html>

![image](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/122253052/c3dd077b-49c2-49ba-a732-c849e4131de2)

**Versions:**  
 - Adapter version: 1.0.2
 - JS-Controller version: v18.18.0
 - Node version: <node-version> 
 - Operating system: raspbian

**Additional context**

**Comment by Gaspode69** [comment]
According to the last screenshot you have still installed version 1.0.0
If you do not get offered 1.1.1 in the adapter overview, press the update symbol at the upper left.

**Comment by Gaspode69** [comment]
According to your Screenshot you have still installed Version 1.0.0.
If you get not offered 1.1.1, try to update the adapter list:
![grafik](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/45949835/30eedebb-bed1-44a8-bf03-b76dd8586816)

**Comment by Gaspode69** [comment]
Try to refresh adapter list:
![grafik](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/45949835/ea7ab7c7-1155-47a1-b758-f927067dbbf4)

**Comment by Gaspode69** [comment]
Fixed in version 1.1.1

**Comment by Gavor69** [comment]
Not already?

![image](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/122253052/30f62951-4c89-45fa-9cdb-3e8a3ae28309)

![image](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/122253052/d45ac7d0-9bae-4dce-a92c-ce5411b247a1)

**Comment by Gavor69** [comment]
I got it!

![image](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/122253052/d8ad4a4d-65eb-44d2-b6bc-2b3c32ad48bb)

**Comment by Gavor69** [comment]
![image](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/122253052/21bacd7f-2021-4562-85ce-c29c211abf97)

**Comment by Gaspode69** [comment]
According to your Screenshot you have still installed Version 1.0.0.
If you get not offered 1.1.1, try to update the adapter list:
![pasted-from-clipboard](https://github.com/Gaspode69/ioBroker.alpha-ess/assets/45949835/421c5c85-bdcf-4916-a5c6-520de9e180f5)
