### ISSUE TITLE
server error in ClosedAPI

### ISSUE THREAD

**Issue by WilliLz** [Gaspode69/ioBroker.alpha-ess#77]
**Describe the bug**  
since 03. Dec, the following error occures:
log: "authenticate Exception occurred: TypeError: Cannot read properties of undefined (reading 'AccessToken')"

**To Reproduce**  
start adapter with "ClosedAPI"
hint: openAPI works fine

**Expected behavior**  

**Versions:**  
 - Adapter version: <1.1.1>
 - JS-Controller version: <5.0.16> 
 - Node version: <18.13.0> 
 - Operating system: <proxmox/VM/debian12>

**Additional context**

**Comment by Gaspode69** [comment]
Closed API no longer supported by Alpha ESS. Please switch to Open API.
V2.0.0 (in beta repository) no longer allows to configure Closed API.
Sorry.

**Comment by WilliLz** [comment]
thanks for your information. I was interested in some information which aren't visible in open API ;)

**Comment by Gaspode69** [comment]
See here:
https://forum.iobroker.net/post/1078312
and here:
https://forum.iobroker.net/post/892023

Which information are you interested in, which are not available in OpenAPI?
Probably we can try it with a feature request for Open API.

**Comment by WilliLz** [comment]
I've now upgraded to version 2.0.0 beta - it works like a charme.
All needed information are available. 
Usually I don't install a beta in my production iobroker. I now set up an other iobroker for testing.
Thank you very much for supporting

**Comment by Gaspode69** [comment]
You are welcome. Thank you for your feedback. Version 2.0 will be available in Stable repository next week.
