### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by Blackhole71** [Gaspode69/ioBroker.alpha-ess#86]
Hello,

when setting the network loading time (alpha-ess.0.Settings_Charge.Charging_period_1_start or other) I get the following error in the protocol

alpha-ess.0 | 2024-01-04 09:18:29.160 | error | Unknown error occurred: null (#1) Group:Settings_Charge
alpha-ess.0 | 2024-01-04 09:18:29.151 | error | Error prforming post request updateChargeConfigInfo: AxiosError: Request failed with status code 404

Versions:
 - Adapter version: 2.0.1
 - NPM: 9.6.7
 - Node version: v18.17.1
 - Operating system: raspbian

It still worked with the Closed API

**Comment by Gaspode69** [comment]
Hi,
this is currently a bug in OpenAPI, see:
https://github.com/alphaess-developer/alphacloud_open_api/issues/59
Ther is nothing I can do in the adapter implementation. Sorry.
